version: 'latest'

services:

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
        - 5432:5432